package com.kachhepati.service;

public interface QueryConstant {

	String VEHICLE_SEARCH = "VEHICLE_SEARCH";

	String VEHICLE_ALL = "VEHICLE_ALL";

	String VEHICLE_SEARCH_VEHICLETYPE = "VEHICLE_SEARCH_VEHICLETYPE";

	String VEHICLE_SEARCH_VEHICLEMAKE = "VEHICLE_SEARCH_VEHICLEMAKE";
	
	String VEHICLE_SEARCH_VEHICLEREGNUM = "VEHICLE_SEARCH_VEHICLEREGNUM";
	
	String VEHICLE_SEARCH_VEHICLE_ID="VEHICLE_SEARCH_VEHICLE_ID";

	String ROUTE_ALL = "ROUTE_ALL";

	String ROUTE_SEARCH = "ROUTE_SEARCH";

	

	String ROUTE_SEARCH_ROUTENAME = "ROUTE_SEARCH_ROUTENAME";
	
	String ROUTE_SEARCH_ROUTE_ID = "ROUTE_SEARCH_ROUTE_ID";

}
